### ISSUE TITLE
Problem recording shoutcast streams

### ISSUE THREAD

**Issue by schulle4u** [beedaddy/radiorec#3]
When trying to record a shoutcast stream, the radiorec script prints the following error. Tested on Debian Jessie using a shoutcast V1 stream. 
Icecast-based streams work as expected. 
[Radiorec_error.txt](https://github.com/beedaddy/radiorec/files/319059/Radiorec_error.txt)

**Comment by beedaddy** [comment]
I don't know... What is the exact entry in settings.ini for this station?

**Comment by schulle4u** [comment]
You can try this one: 

`rmn = http://rmnradio.powerstream.de:8022`

Tested with various shoutcast V1 streams. As it seems the script looks for an .mp3 extension at the end of the URL. I also tried modifying the URL like this: 

`rmn = http://rmnradio.powerstream.de:8022/;stream.mp3`

The semicolon before stream.mp3 is requiered by shoutcast if you need to add the extension. However this either results in the same error or prints an "invalid port" error. 

Steffen

**Comment by beedaddy** [comment]
Sorry I have currently no time to investigate into this. Shoutcast streams are currently not supported. But of course PRs are welcome.
