### ISSUE TITLE
Not compatible with OS X

### ISSUE THREAD

**Issue by willwhy** [beedaddy/radiorec#4]
Line 48 in radiorec.py could add another condition to compatible with OS X.

**Comment by beedaddy** [comment]
Sorry but I have no clue about OS X. Without help, OS X continues to be unsupported.

**Comment by mro** [comment]
config would IMO usually go into

    $HOME/Library/Application\ Support/radiorec/

on OSX. If that's all that prevents OSX usage, that should be feasible.

@geekoala do you want to give it a try?

**Comment by beedaddy** [comment]
So... I have no idea if it works, but the latest commit might add support for OS X. :-)
Perhaps someone could give it a try?

**Comment by mro** [comment]
on OSX El Capitan (10.11.6 (15G1004)) and aad7f56:

```
$ ./radiorec.py 
env: python3: No such file or directory
```

**Comment by beedaddy** [comment]
@mro But ... python3 is installed?

**Comment by mro** [comment]
no.
