### ISSUE TITLE
Starting without argument 

### ISSUE THREAD

**Issue by lastsamurai26** [beedaddy/radiorec#9]
I do not know if this is really a mistake, but if you start radiorec.py without an argument, this will come out. I've tried to fix it but have not made it yet. Maybe you can find the issue 

MacOSX 10.12.6 and Debian9 with python 3.6

Started as ./radiorec.py 

without record or list 

```
Traceback (most recent call last):
  File "./radiorec.py", line 161, in <module>
    main()
  File "./radiorec.py", line 158, in main
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by beedaddy** [comment]
You're right. Please check again from master with the latest commit c65e34b283545df606c730ad59d91dc02ee46905.

**Comment by lastsamurai26** [comment]
Out put with new master commit 
```

Error: No argument specified.

usage: radiorec.py [-h] {record,list} ...

This program records internet radio streams. It is free software and comes
with ABSOLUTELY NO WARRANTY.

positional arguments:
  {record,list}  sub-command help
    record       Record a station
    list         List all known stations

optional arguments:
  -h, --help     show this help message and exit
```


:) solved thx
